"""Re-export all 68 DPM Django models."""

from dpmcore.django.models.auxiliary import (
    AuxCellMapping,
    AuxCellStatus,
    ModelViolations,
)
from dpmcore.django.models.glossary import (
    Category,
    CompoundItemContext,
    Context,
    ContextComposition,
    Item,
    ItemCategory,
    Property,
    PropertyCategory,
    SubCategory,
    SubCategoryItem,
    SubCategoryVersion,
    SupercategoryComposition,
)
from dpmcore.django.models.infrastructure import (
    Changelog,
    ChangelogAttribute,
    Concept,
    ConceptRelation,
    DataType,
    Document,
    DocumentVersion,
    DpmAttribute,
    DpmClass,
    Language,
    Organisation,
    Reference,
    RelatedConcept,
    Release,
    Role,
    Subdivision,
    SubdivisionType,
    Translation,
    User,
    UserRole,
    VariableGeneration,
)
from dpmcore.django.models.operations import (
    OperandReference,
    OperandReferenceLocation,
    Operation,
    OperationNode,
    OperationScope,
    OperationScopeComposition,
    OperationVersion,
    OperationVersionData,
    Operator,
    OperatorArgument,
)
from dpmcore.django.models.packaging import (
    Framework,
    Module,
    ModuleParameters,
    ModuleVersion,
    ModuleVersionComposition,
    OperationCodePrefix,
)
from dpmcore.django.models.rendering import (
    Cell,
    Header,
    HeaderVersion,
    KeyHeaderMapping,
    Table,
    TableAssociation,
    TableGroup,
    TableGroupComposition,
    TableVersion,
    TableVersionCell,
    TableVersionHeader,
)
from dpmcore.django.models.variables import (
    CompoundKey,
    KeyComposition,
    Variable,
    VariableCalculation,
    VariableVersion,
)

__all__ = [
    # auxiliary
    "AuxCellMapping",
    "AuxCellStatus",
    "ModelViolations",
    # glossary
    "Category",
    "CompoundItemContext",
    "Context",
    "ContextComposition",
    "Item",
    "ItemCategory",
    "Property",
    "PropertyCategory",
    "SubCategory",
    "SubCategoryItem",
    "SubCategoryVersion",
    "SupercategoryComposition",
    # infrastructure
    "Changelog",
    "ChangelogAttribute",
    "Concept",
    "ConceptRelation",
    "DataType",
    "Document",
    "DocumentVersion",
    "DpmAttribute",
    "DpmClass",
    "Language",
    "Organisation",
    "Reference",
    "RelatedConcept",
    "Release",
    "Role",
    "Subdivision",
    "SubdivisionType",
    "Translation",
    "User",
    "UserRole",
    "VariableGeneration",
    # operations
    "OperandReference",
    "OperandReferenceLocation",
    "Operation",
    "OperationNode",
    "OperationScope",
    "OperationScopeComposition",
    "OperationVersion",
    "OperationVersionData",
    "Operator",
    "OperatorArgument",
    # packaging
    "Framework",
    "Module",
    "ModuleParameters",
    "ModuleVersion",
    "ModuleVersionComposition",
    "OperationCodePrefix",
    # rendering
    "Cell",
    "Header",
    "HeaderVersion",
    "KeyHeaderMapping",
    "Table",
    "TableAssociation",
    "TableGroup",
    "TableGroupComposition",
    "TableVersion",
    "TableVersionCell",
    "TableVersionHeader",
    # variables
    "CompoundKey",
    "KeyComposition",
    "Variable",
    "VariableCalculation",
    "VariableVersion",
]
